// ---------------------------------------------------------------------------
// PHASE 0 — THE LANGUAGE LAYER
// One declarative table drives highlighting, brackets, snippets, symbols,
// breadcrumbs, diagnostics and AI context for 80+ languages. No compiler,
// no per-language extension required.
// ---------------------------------------------------------------------------
const K = s => new Set(String(s).split(/\s+/).filter(Boolean));
const PAIRS = { "{":"}", "(":")", "[":"]", "<":">" };
const OPENERS = ["{","(","[","\"","'","`"];

const FAM = {
  c:    { line:["//"], block:[["/*","*/"]], str:[['"','"'],["'","'"]], esc:true, pairs:PAIRS, ind:2, regexp:true },
  h:    { line:["#"],  str:[['"""','"""'],['"','"'],["'","'"]], esc:true, raw:['"""'], pairs:PAIRS, ind:4 },
  sql:  { line:["--"], block:[["/*","*/"]], str:[['"','"'],["'","'"]], esc:false, pairs:{}, ind:2 },
  lisp: { line:[";"],  str:[['"','"'],["'","'"]], esc:true, pairs:PAIRS, ind:2 },
  lua:  { line:["--"], str:[['[[',']]'],['"','"'],["'","'"]], esc:true, pairs:PAIRS, ind:2 },
  hs:   { line:["--"], block:[["{-","-}"]], str:[['"','"'],["'","'"]], esc:true, pairs:PAIRS, ind:2 },
  m:    { xml:true, str:[['"','"'],["'","'"]], esc:true, pairs:{}, ind:2 },
  vb:   { line:["'"],  str:[['"','"'],["'","'"]], esc:false, pairs:{}, ind:2 },
  pct:  { line:["%"],  str:[['"','"'],["'","'"]], esc:true, pairs:{}, ind:2 },
  scm:  { line:[";"],  str:[['"','"'],["'","'"]], esc:true, pairs:PAIRS, ind:2 },
  plain:{ str:[['"','"'],["'","'"]], pairs:{}, ind:2 },
  md:   { line:[], str:[], pairs:{}, ind:2, markdown:true },
};

// ---- symbol extraction recipes: [kind, regexSource, group]
const SYM = {
  py:   [["fn","^([ \\t]*)(?:async[ \\t]+)?def[ \\t]+([A-Za-z_]\\w*)",2],["cls","^([ \\t]*)class[ \\t]+([A-Za-z_]\\w*)",2],
         ["var","^([ \\t]*)([A-Z][A-Z0-9_]{2,})[ \\t]*=",2]],
  rb:   [["fn","^([ \\t]*)def[ \\t]+(?:self\\.)?([A-Za-z_]\\w*[!?=]?)",2],["cls","^([ \\t]*)class[ \\t]+([A-Za-z_]\\w*)",2],
         ["mod","^([ \\t]*)module[ \\t]+([A-Za-z_]\\w*)",2]],
  js:   [["fn","(?:^|[^\\w$.])(?:export[ \\t]+)?(?:default[ \\t]+)?(?:async[ \\t]+)?function[ \\t*]*([A-Za-z_$][\\w$]*)",1],
         ["cls","(?:^|[^\\w$.])(?:export[ \\t]+)?(?:abstract[ \\t]+)?class[ \\t]+([A-Za-z_$][\\w$]*)",1],
         ["var","(?:^|\\n)[ \\t]*(?:export[ \\t]+)?(?:const|let|var)[ \\t]+([A-Za-z_$][\\w$]*)",1],
         ["fn","(?:^|\\n)[ \\t]*(?:export[ \\t]+)?(?:const|let|var)[ \\t]+([A-Za-z_$][\\w$]*)[ \\t]*=[ \\t]*(?:async[ \\t]*)?(?:function|\\([^)]*\\)[ \\t]*=>|[A-Za-z_$][\\w$]*[ \\t]*=>)",1],
         ["fn","(?:^|[^\\w$.])(?:export[ \\t]+)?(?:const|let|var)[ \\t]*\\{([^}]*)\\}[ \\t]*=[ \\t]*(?:async[ \\t]*)?function",1]],
  ts:   [["int","(?:^|\\n)[ \\t]*(?:export[ \\t]+)?(?:declare[ \\t]+)?(?:interface|type|enum)[ \\t]+([A-Za-z_$][\\w$]*)",1],
         ["cls","(?:^|[^\\w$.])(?:export[ \\t]+)?(?:abstract[ \\t]+)?class[ \\t]+([A-Za-z_$][\\w$]*)",1],
         ["fn","(?:^|[^\\w$.])(?:export[ \\t]+)?(?:async[ \\t]+)?function[ \\t*]*([A-Za-z_$][\\w$]*)",1],
         ["var","(?:^|\\n)[ \\t]*(?:export[ \\t]+)?(?:const|let|var)[ \\t]+([A-Za-z_$][\\w$]*)",1]],
  jvm:  [["cls","(?:^|[^\\w$.])((?:public|private|protected|static|final|abstract|sealed|open|internal|override|suspend)[ \\t]+)+(?:class|interface|enum|record|object)[ \\t]+([A-Za-z_]\\w*)",2],
         ["fn","(?:^|[^\\w$.])((?:public|private|protected|static|final|abstract|override|suspend|inline|operator)[ \\t]+)*[\\w<>\\[\\],. ?]+[ \\t]+([A-Za-z_]\\w*)[ \\t]*\\(",2],
         ["int","(?:^|\\n)[ \\t]*((?:public|private|protected|static|final|abstract)[ \\t]+)*(?:interface|enum|record)[ \\t]+([A-Za-z_]\\w*)",2]],
  c:    [["prm","^([ \\t]*#[ \\t]*define[ \\t]+)([A-Za-z_]\\w*)",2],
         ["fn","^[A-Za-z_][\\w \\t\\*]*?([A-Za-z_]\\w*)[ \\t]*\\([^;]*\\)[ \\t]*\\{",1],
         ["int","^[ \\t]*(?:typedef[ \\t]+)?(?:struct|enum|union)[ \\t]+([A-Za-z_]\\w*)",1]],
  rust: [["fn","^[ \\t]*(?:pub(?:\\([^)]*\\))?[ \\t]+)?(?:async[ \\t]+)?(?:unsafe[ \\t]+)?(?:extern[ \\t]+\"[^\"]+\"[ \\t]+)?fn[ \\t]+([A-Za-z_]\\w*)",1],
         ["int","^[ \\t]*(?:pub(?:\\([^)]*\\))?[ \\t]+)?(?:struct|enum|trait|union|type|mod)[ \\t]+([A-Za-z_]\\w*)",1],
         ["int","^[ \\t]*impl(?:<[^>]*>)?[ \\t]+([A-Za-z_][\\w:]*)",1],
         ["var","^[ \\t]*macro_rules![ \\t]+([A-Za-z_]\\w*)",1]],
  go:   [["fn","^[ \\t]*func[ \\t]+(?:\\([^)]*\\)[ \\t]*)?([A-Za-z_]\\w*)",1],
         ["fn","^[ \\t]*func[ \\t]+([A-Za-z_]\\w*)",1],
         ["int","^[ \\t]*type[ \\t]+([A-Za-z_]\\w*)",1]],
  sh:   [["fn","^[ \\t]*(?:function[ \\t]+)?([A-Za-z_]\\w*)[ \\t]*\\(\\)[ \\t]*\\{",1],
         ["var","^([ \\t]*(?:export[ \\t]+|local[ \\t]+|declare[ \\t]+)?)([A-Za-z_]\\w*)=",2]],
  lua:  [["fn","^[ \\t]*(?:local[ \\t]+)?function[ \\t]+([A-Za-z_.:]+)",1],
         ["var","^[ \\t]*local[ \\t]+([A-Za-z_]\\w*)[ \\t]*=",1]],
  php:  [["cls","(?:^|\\n)[ \\t]*(?:final[ \\t]+|abstract[ \\t]+)?(?:class|interface|trait)[ \\t]+([A-Za-z_]\\w*)",1],
         ["fn","(?:^|[^\\w$.])function[ \\t]+([A-Za-z_]\\w*)",1],
         ["var","(?:^|\\n)[ \\t]*\\$([A-Za-z_]\\w*)[ \\t]*=",1]],
  swift:[["fn","(?:^|\\n)[ \\t]*(?:public[ \\t]+|private[ \\t]+|internal[ \\t]+|fileprivate[ \\t]+|open[ \\t]+|static[ \\t]+|final[ \\t]+|override[ \\t]+|mutating[ \\t]+)*(?:func)[ \\t]+([A-Za-z_]\\w*)",1],
         ["cls","(?:^|\\n)[ \\t]*(?:public[ \\t]+|private[ \\t]+|internal[ \\t]+|fileprivate[ \\t]+|open[ \\t]+|final[ \\t]+)*(?:class|struct|enum|protocol|extension|typealias)[ \\t]+([A-Za-z_]\\w*)",1],
         ["var","(?:^|\\n)[ \\t]*(?:public[ \\t]+|private[ \\t]+|internal[ \\t]+|static[ \\t]+|let[ \\t]+|var[ \\t]+)([A-Za-z_]\\w*)[ \\t]*:",1]],
  kt:   [["cls","(?:^|\\n)[ \\t]*(?:public[ \\t]+|private[ \\t]+|internal[ \\t]+|open[ \\t]+|abstract[ \\t]+|sealed[ \\t]+|data[ \\t]+)*(?:class|interface|object|enum class)[ \\t]+([A-Za-z_]\\w*)",1],
         ["fn","(?:^|\\n)[ \\t]*(?:public[ \\t]+|private[ \\t]+|internal[ \\t]+|open[ \\t]+|override[ \\t]+|suspend[ \\t]+|inline[ \\t]+)*(?:fun)[ \\t]+([A-Za-z_]\\w*)",1],
         ["var","(?:^|\\n)[ \\t]*(?:val|var)[ \\t]+([A-Za-z_]\\w*)",1]],
  cs:   [["cls","(?:^|\\n)[ \\t]*((?:public|private|protected|internal|static|sealed|abstract|partial|record)[ \\t]+)*(?:class|interface|struct|enum|record)[ \\t]+([A-Za-z_]\\w*)",2],
         ["fn","(?:^|\\n)[ \\t]*((?:public|private|protected|internal|static|async|virtual|override|sealed)[ \\t]+)+[\\w<>\\[\\],.?]+[ \\t]+([A-Za-z_]\\w*)[ \\t]*\\(",2]],
  dart: [["cls","(?:^|\\n)[ \\t]*(?:abstract[ \\t]+)?class[ \\t]+([A-Za-z_]\\w*)",1],
         ["fn","(?:^|\\n)[ \\t]*(?:static[ \\t]+)?(?:[\\w<>?]+[ \\t]+)?([A-Za-z_]\\w*)[ \\t]*\\([^)]*\\)[ \\t]*(?:async[ \\t]*)?\\{",1]],
  scala:[["cls","(?:^|\\n)[ \\t]*(?:(?:final|sealed|abstract|case|implicit|private|protected)[ \\t]+)*(?:class|object|trait|enum)[ \\t]+([A-Za-z_]\\w*)",1],
         ["fn","(?:^|\\n)[ \\t]*(?:private[ \\t]+|override[ \\t]+)?def[ \\t]+([A-Za-z_]\\w*)",1]],
  r:    [["fn","\\b([A-Za-z_.][\\w.]*)[ \\t]*(?:<-|=)[ \\t]*function[ \\t]*\\(",1],
         ["var","^([A-Za-z_.][\\w.]*)[ \\t]*(?:<-|=)[ \\t]*(?!function)",1]],
  mat:  [["fn","^[ \\t]*function[ \\t]+([^\\n(]+)",1],["var","^([ \\t]*)([A-Za-z_]\\w*)[ \\t]*=",2]],
  jul:  [["fn","^[ \\t]*(?:function|macro)[ \\t]+([A-Za-z_]\\w*)",1],
         ["int","^[ \\t]*(?:abstract[ \\t]+)?(?:mutable[ \\t]+)?struct[ \\t]+([A-Za-z_]\\w*)",1],
         ["fn","^[ \\t]*([A-Za-z_]\\w*)[ \\t]*\\([^)]*\\)[ \\t]*(?:where[ \\n\\S]*?)?=",1]],
  hs:   [["fn","^([ \\t]*)([A-Za-z_]\\w*)[ \\t]*::",2],["int","^(?:data[ \\t]+|newtype[ \\t]+|type[ \\t]+|class[ \\t]+)?([A-Z]\\w*)[ \\t]*(?:\\(|=|;|$)",1]],
  erl:  [["fn","^([ \\t]*)([a-z][\\w@]*)[ \\t]*\\(",2]],
  ex:   [["fn","^([ \\t]*)def(?:p)?[ \\t]+([A-Za-z_][\\w!?]*)",2],["mod","^([ \\t]*)defmodule[ \\t]+([A-Za-z_.]+)",2]],
  zig:  [["fn","^[ \\t]*(?:pub[ \\t]+)?fn[ \\t]+([A-Za-z_]\\w*)",1]],
  nim:  [["fn","^[ \\t]*(?:proc|func|method|iterator|template|macro)[ \\t]+([A-Za-z_]\\w*)",1],["int","^[ \\t]*type[ \\t]+([A-Za-z_]\\w*)",1]],
  sol:  [["fn","^[ \\t]*(?:function|constructor)[ \\t]+([A-Za-z_]\\w*)",1],
         ["int","^(?:contract|library|interface)[ \\t]+([A-Za-z_]\\w*)",1],
         ["fn","^[ \\t]*(?:event|modifier|fallback|receive)[ \\t]+([A-Za-z_]\\w*)",1]],
  elm:  [["fn","^([ \\t]*)([a-z]\\w*)[ \\t]*:.*->",2],["int","^([ \\t]*)(type alias)[ \\s\\S]*?^([ \\t]*)type[ \\t]+([A-Z]\\w*)",3]],
  ocaml:[["let","^([ \\t]*)(?:let[ \\t]+(?:rec[ \\t]+)?)([A-Za-z_]\\w*)",2],["ty","^([ \\t]*)(type[ \\t]+)([a-z]\\w*)",2]],
  clj:  [["fn","^\\(\\s*defn?-?\\s+([A-Za-z_\\-*+!?<>=/.$%&|]+)",1],["fn","^\\(\\s*([A-Za-z_\\-*+!?<>=/.$%&|]+)",1]],
  elm2:[],
  ml:   [["fn","^[ \\t]*(?:let|and)[ \\t]+([a-z_][\\w']*)",1],["int","^[ \\t]*type[ \\t]+([a-z_][\\w']*)",1]],
  groovy:[["cls","(?:^|\\n)[ \\t]*(?:public|final|abstract|static)*[ \\t]*(?:class|interface|trait|enum)[ \\t]+([A-Za-z_]\\w*)",1],
         ["fn","(?:^|\\n)[ \\t]*(?:public|private|protected|static|def)[ \\t]+([A-Za-z_]\\w*)[ \\t]*\\(",1]],
  objc: [["fn","^[ \\t]*[-+]\\s*\\([^)]*\\)\\s*([A-Za-z_]\\w*)",1]],
  asm:  [["fn","^[ \\t]*([A-Za-z_.$][\\w.$]*):",1]],
  abap: [["fn","^[ \\t]*(?:METHODS|FORM|PROCEDURE)[ \\t]+([A-Za-z_/]\\w*)",1]],
  pas:  [["fn","^[ \\t]*(?:function|procedure|constructor|destructor)[ \\t]+([A-Za-z_]\\w*)",1],
         ["int","^[ \\t]*(?:type|unit)[ \\t]+([A-Za-z_]\\w*)",1]],
  for:  [["fn","^[ \\t]*program[ \\t]+([A-Za-z_]\\w*)",1],
         ["fn","^[ \\t]*(?:integer|real|logical|character|double[ \\t]+precision|subroutine[ \\t]+[a-z]+)[ \\t]+function[ \\t]+([A-Za-z_]\\w*)",1]],
  cob:  [["fn","^([ \\t]*)([A-Za-z-]+?)[ \\t]+(?:PIC|SECTION|DIVISION)",2]],
  adb:  [["fn","^([ \\t]*)(?:local[ \\t]+)?function[ \\t]+([A-Za-z_]\\w*)",2],["proc","^([ \\t]*)(?:package[ \\t]+body)[ \\s\\S]*?^([ \\t]*)([A-Za-z_]\\w*)[ \\t]*\\(.*\\)[ \\t]*(?:is|as)[ \\s\\S]*?\\1end[ \\t]+\\2",2]],
  vhdl:[["fn","^([ \\t]*)(?:entity|architecture|component|package)[ \\s\\S]*?^([ \\t]*)([A-Za-z_]\\w*)[ \\s\\S]*?^\\1is",3]],
  verilog:[["fn","^[ \\t]*(?:function|task)[ \\t]+(?:automatic[ \\t]+)?([A-Za-z_]\\w*)",1],["mod","^[ \\t]*module[ \\t]+([A-Za-z_]\\w*)",1]],
  txt:  [],
};