// ---- keyword / builtin / type / constant vocabularies
const KW = {
  js: "break case catch class const continue debugger default delete do else export extends finally for function if import in instanceof let new of return static super switch this throw try typeof var void while with yield async await get set of from as public private protected implements interface enum abstract declare namespace module",
  ts: "break case catch class const continue debugger default delete do else export extends finally for function if import in instanceof let new of return static super switch this throw try typeof var void while with yield async await abstract as asserts implements interface is keyof namespace readonly satisfies type enum infer module declare",
  py: "and as assert async await break class continue def del elif else except finally for from global if import in is lambda nonlocal not or pass raise return try while with yield match case self cls",
  java:"abstract assert boolean break byte case catch char class const continue default do double else enum extends final finally float for if implements import instanceof int interface long native new package private protected public return short static strictfp super switch synchronized this throw throws transient try var void volatile while record sealed permits yield",
  c:  "auto break case char const continue default do double else enum extern float for goto if inline int long register restrict return short signed sizeof static struct switch typedef union unsigned void volatile while bool true false NULL",
  cpp:"alignas alignof and asm auto bool break case catch char char8_t char16_t char32_t class concept const consteval constexpr constinit const_cast continue co_await co_return co_yield decltype default delete do double dynamic_cast else enum explicit export extern false float for friend goto if inline int long mutable namespace new noexcept nullptr operator private protected public register reinterpret_cast requires return short signed sizeof static static_assert static_cast struct switch template this thread_local throw true try typedef typeid typename union unsigned using virtual void volatile wchar_t while",
  cs: "abstract as base bool break byte case catch char checked class const continue decimal default delegate do double dynamic else enum event explicit extern false finally fixed float for foreach goto if implicit in int interface internal is lock long namespace new null object operator out override params private protected public readonly ref return sbyte sealed short sizeof stackalloc static string struct switch this throw true try typeof uint ulong unchecked unsafe ushort using var virtual void volatile while yield async await record required init",
  go: "break case chan const continue default defer else fallthrough for func go goto if import interface map package range return select struct switch type var nil true false string int int8 int16 int32 int64 uint uint8 uint16 uint32 uint64 byte rune float32 float64 bool error any",
  rust:"as async await break const continue crate dyn else enum extern false fn for if impl in let loop match mod move mut pub ref return self Self static struct super trait true type unsafe use where while box i8 i16 i32 i64 u8 u16 u32 u64 usize f32 f64 bool char str String Vec Option Result Some None Ok Err",
  rb:  "BEGIN END alias and begin break case class def defined? do else elsif end ensure false for if in module next nil not or redo rescue retry return self super then true undef unless until when while yield attr_accessor attr_reader attr_writer require require_relative puts",
  php: "abstract and array as break callable case catch class clone const continue declare default do echo else elseif empty enddeclare endfor endforeach endif endswitch endwhile enum extends final finally fn for foreach function global goto if implements include include_once instanceof insteadof interface isset list match namespace new or print private protected public readonly require require_once return static switch throw trait try unset use var while xor yield true false null int string float bool void iterable object mixed never",
  swift:"associatedtype class deinit enum extension fileprivate func import init inout internal let open operator private protocol public rethrows static struct subscript typealias var break case continue default defer do else fallthrough for guard if in repeat return switch where while as Any catch false is nil rethrows self Self super throw throws true try",
  kt:  "abstract actual annotation as break by catch class companion const constructor continue crossinline data delegate do dynamic else enum expect external final finally for fun get if import in infix init inline inner interface internal is lateinit noinline null object open operator out override package private protected public reified return sealed set super suspend tailrec this throw try typealias typeof val var vararg when where while yield",
  scala:"abstract case catch class def do else extends false final finally for forSome if implicit import lazy match new null object override package private protected return sealed super this throw trait try true type val var while with yield",
  dart: "abstract as assert async await break case catch class const continue covariant default deferred do dynamic else enum export extends extension external factory false final finally for get hide if implements import in interface is late library mixin new null on operator part required rethrow return sealed set show static super switch sync this throw true try typedef var void while with yield",
  php2:"",
  hs:  "case class data default deriving do else foreign if import in infix infixl infixr instance let module newtype of then type where forall mdo proc rec family role pattern static group by using qualified",
  lua: "and break do else elseif end false for function goto if in local nil not or repeat return then true until while",
  sh:  "if then else elif fi case esac for while until do done in function select time case esac return export local readonly declare shift source alias unalias trap set unset",
  ex:  "def defp defmodule defmacro defstruct defpprotocol defimpl use import require alias require import quote unquote sigil when with for cond case receive try rescue catch after else raise throw defdelegate defguard defprotocol",
  r:   "if else repeat while function for next break TRUE FALSE NULL Inf NaN NA library require source c list vector data.frame matrix factor",
  jl:  "function end if elseif else for while break continue return struct mutable abstract type where begin let quote in isa import using module export public baremodule",
  rs:  "fn let mut struct enum impl trait use mod pub crate match if else loop for while return const static type where as ref dyn unsafe async await move box Self super",
  ml:  "fun let rec and in end type val of ref with exception raise try handle open struct signature functor when",
  clj: "defn defn- def defmacro defmulti defmethod defprotocol defrecord deftype let letfn if when when-not cond case do comment ns import require use recur loop for doseq dotool fn quote var set! binding",
  kt2: "",
  erl: "-module -export -record -spec -type -define -include",
  nim: "proc func method iterator template macro type var let const result object ref ptr seq",
  zig: "const var fn pub usingnamespace struct enum union test defer comptime errdefer if switch while for orelse try catch unreachable",
  sol: "pragma import library contract interface constructor function event modifier fallback receive returns returns emit using for struct mapping enum error require",
  raku: "sub method class role grammar token rule has is does unit module package constant my our state submethod multi",
  for: "program end subroutine function module use implicit none integer real dimension parameter contains stop",
  cob:  "IDENTIFICATION DIVISION PROGRAM-ID ENVIRONMENT-DATA CONFIGURATION-SOURCE DATA WORKING-STORAGE PROCEDURE DIVISION DISPLAY STOP RUN PIC VALUE.",
  pas: "begin end program unit uses var const type function procedure record class object interface implementation constructor destructor property private public inherited",
  abap: "DATA TYPES BEGIN OF END OF FORM IF ELSE ELSEIF ENDIF LOOP ENDLOOP DO WHILE WHEN CASE ENDCASE METHOD METHODS CLASS ENDCLASS REPORT SELECT ENDSELECT",
  verilog:"module endmodule input output inout wire reg always always_ff always_comb initial begin end assign parameter localparam generate endgenerate if else case endcase function endfunction task endtask",
  asm:  "mov push pop call ret jmp je jne cmp add sub lea nop int xor",
  vhdl:"entity architecture is port map signal process begin end component of downto to in out inout type subtype function procedure variable constant",
  adb: "with Ada.Text_IO use package body procedure function is record type begin end loop if then else return pragma",
  vb:  "Dim Sub Function Class Module If Then Else For Each Next While End Select Case New Me Return Public Private Friend Property End Module",
  objc:"@interface @implementation @end @property @synthesize @dynamic @protocol @selector @class @public @private @protected @autoreleasepool instancetype nonatomic atomic strong weak copy assign readonly",
  powershell:"function param begin process end if else elseif foreach for while do switch return class enum filter where select foreach-object write-output write-host",
  batch:"set call goto if else for in do exit not exist defined errorlevel equ goto eof rem",
  make:"ifeq ifneq ifdef ifndef else endif include define endef export unexport vpath .PHONY",
  cmake:"if elseif else endif foreach endforeach function endfunction macro endmacro set list string file add_executable add_library target_sources include_directories",
  tex:  "documentclass usepackage begin end document section subsection subsubsection chapter item label ref cite includegraphics newcommand renewcommand textbf textit",
  org:  "#+TITLE #+AUTHOR #+OPTIONS * heading",
  csv:  "",
};
const BUILTINS = {
  js: "console window document Math JSON Object Array String Number Boolean Promise Map Set WeakMap WeakSet Symbol Date RegExp Error parseInt parseFloat isNaN isFinite setTimeout setInterval clearTimeout clearInterval fetch localStorage sessionStorage require module exports globalThis process Buffer require process URL URLSearchParams TextEncoder TextDecoder queueMicrotask structuredClone super",
  py: "print len range enumerate zip map filter sorted sum min max abs round open input int float str bool list dict set tuple type isinstance issubclass super getattr setattr hasattr repr format any all dir vars id hash iter next slice reversed divmod pow chr ord bin hex oct callable staticmethod classmethod property Exception ValueError TypeError KeyError IndexError AttributeError RuntimeError NotImplementedError StopIteration self cls",
  rb: "puts print p pp require require_relative attr_accessor attr_reader attr_writer lambda proc loop new freeze nil raise rescue begin ensure self",
  java:"System out println print String Integer Long Double Float Boolean Math List ArrayList Map HashMap Set HashSet Stream Optional Objects Arrays Collections Exception RuntimeException Thread Runnable",
  c:  "printf scanf malloc calloc realloc free memcpy memset strlen strcpy strcmp fopen fclose fgets fputs fprintf sprintf sqrt pow abs rand srand exit malloc",
  cpp:"std cout cin endl string vector map set unordered_map unique_ptr shared_ptr nullptr std::move std::forward make_unique make_shared",
  go: "fmt Println Printf Sprintf Errorf Error New Reader Writer String Len Cap Make Append Copy Close Scan os io bufio http json time strconv strings sync context errors reflect sort",
  rust:"println! print! eprintln! format! vec! String Vec Option Result Some None Ok Err Box Rc Arc RefCell Cell HashMap HashSet std::mem std::fmt",
  sh:  "echo cd ls cat grep sed awk cut tr sort uniq head tail wc find xargs rm cp mv mkdir chmod chown curl wget git python python3 node npm pip apt sudo export source exit set test read local return",
  lua: "print type pairs ipairs table string math io os require tonumber tostring pcall error assert select unpack rawget rawset setmetatable getmetatable",
  php: "echo print count strlen str_replace array_map array_filter implode explode json_encode json_decode var_dump isset empty is_array is_null in_array",
  swift:"print String Int Double Bool Array Dictionary Set Optional UIKit Foundation SwiftUI View Text func let var guard if",
  r:   "c list print paste apply sapply lapply vapply mapply filter map reduce summary head tail",
  jl:  "println print length size push! pop! zeros ones rand Array Vector Dict String Int Float println push! zeros",
  ex:  "IO IO.inspect Kernel defmodule defstruct use",
  sql: "SELECT FROM WHERE INSERT UPDATE DELETE CREATE DROP ALTER TABLE INDEX VIEW JOIN LEFT RIGHT INNER OUTER FULL ON GROUP BY ORDER HAVING LIMIT OFFSET UNION ALL DISTINCT AS AND OR NOT NULL IS IN BETWEEN LIKE EXISTS CASE WHEN THEN ELSE END PRIMARY KEY FOREIGN REFERENCES DEFAULT CONSTRAINT VALUES SET INTO COUNT SUM AVG MIN MAX COALESCE",
  html:"",
};
const TYPES = {
  ts: "string number boolean any unknown never void object symbol bigint Record Partial Required Readonly Pick Omit Map Set Promise Array",
  java:"String Integer Long Double Float Boolean Object List Map Set ArrayList HashMap Exception byte short char int long float double void boolean",
  c:  "int char long short float double void size_t ssize_t int8_t int32_t int64_t uint8_t bool FILE va_list",
  cpp:"int char long short float double void bool auto std string vector map size_t uint8_t",
  go: "int int8 int16 int32 int64 uint uint8 uint16 uint32 uint64 byte rune float32 float64 bool error string any struct interface map chan",
  rust:"i8 i16 i32 i64 u8 u16 u32 u64 usize isize f32 f64 bool char str String Vec Option Result Box Rc Arc",
  ts2:"",
  swift:"String Int Double Float Bool Array Dictionary Set Character Any AnyObject",
  kt:  "String Int Double Float Boolean Long Byte Short Char ArrayList List MutableList Set Map Unit Nothing",
  cs:  "string int long bool double float decimal object byte char var dynamic List Dictionary Task",
  rb:  "String Integer Float Array Hash Symbol Range Proc Struct Class Module Kernel",
  py:  "int float str bool list dict set tuple bytes object None Exception",
};
const CONSTS = {
  js: "true false null undefined NaN Infinity globalThis",
  py: "True False None NotImplemented Ellipsis __name__ __main__ __file__",
  java:"true false null",
  go: "true false nil iota",
  rust:"true false None Some Ok Err",
  c:  "true false NULL",
  cpp:"true false nullptr",
  rb:  "true false nil __FILE__ __LINE__",
  sh:  "true false",
  lua: "true false nil",
  swift:"true false nil",
};